### ISSUE TITLE
Let's replace child_process with Webworker on node

### ISSUE THREAD

**Issue by dre-hh** [parallel-js/parallel.js#100]
What would you think of using https://github.com/audreyt/node-webworker-threads
It has the same api as webworker.
Would you accept such a pull request?

**Comment by Sebmaster** [comment]
Yes, however:

* needs to be an optional dependency, would be even better if it was a peer-dependency or something, I think the user should explicitly opt-in to such a modification
* needs to be stubbed / disabled in browsers
* needs to keep the API backwards compatible

**Comment by dre-hh** [comment]
If you want this to be optional there is an issue with peer dependencies. If paralleljs would specify a peer dependency on webworker-threads, so on install it would warn if webworker-threads is not available.
So i think [optional dependency is just fine][1]
[1]: https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by Sebmaster** [comment]
Yep, just needs to be configurable I think.
