### ISSUE TITLE
Ability to use transferable objects inside Parallel.js

### ISSUE THREAD

**Issue by blackrabbit99** [parallel-js/parallel.js#106]
Clonning data works to long for image's source. What are you thinking about [transferable objects](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_%28transferable_objects%29)

Now I'm making monkey patching for TS interface i can create PR for it.

**Comment by icodeforlove** [comment]
Task.js supports transferable objects

https://github.com/icodeforlove/task.js
