### ISSUE TITLE
npm installs old version

### ISSUE THREAD

**Issue by rmckeel** [parallel-js/parallel.js#107]
I kept trying to figure out why the simple environment-passing example didn't work for Node.js.  It turns out, an 'npm i paralleljs' installs a version from ~3 years ago, before the environment passing feature was added!

I md5 hashed the latest from lib/parallel.js vs my default from npm and realized it was different, otherwise I would have given up on the library as a simple example didn't work.

Please update npm!  Seem like a great library, looking forward to diving in more.

Thanks,

  Ryan

**Comment by rma4ok** [comment]
@adambom are you still planning to maintain this library ?

**Comment by mathiasrw** [comment]
New people have been added to this project

[![Throughput Graph](https://graphs.waffle.io/parallel-js/parallel.js/throughput.svg)](https://waffle.io/parallel-js/parallel.js/metrics/throughput)

Please help out by still adding issues that needs to be fixed

We are working on getting access to npm to update
