### ISSUE TITLE
Limitations on passing environment variables?

### ISSUE THREAD

**Issue by Shadowstep33** [parallel-js/parallel.js#110]
I can't seem to get a variable into global.env. 

```
var SysNaga = {
    players: {},
    biomes: {},
    critters: {}
};
        var par = new Parallel([char],,{
                            env: {
                                a: SysNaga
                            }
                        });

            par.require(Progera);

            par.spawn(Synapse.updatePlayer).then(eLog);
```

SysNaga gets filled with objects of a custom class, but for testing purposes I am leaving it empty. Conversely, I can successfully transmit a primitive such as an int or string. In updatePlayer i console log global.env and it is an empty object literal. Any one have any suggestions?

**Comment by Shadowstep33** [comment]
I seem to have gotten it working, but haven't really tested it. I modified extend in parallel.js

```
	function extend(from, to) {
		if (!to) to = {};
		for (var i in from) {
			to[i] = from[i];
		}
		return to;
	}
```

and I also changed the extend call in Parallel()

```
...
		this.options = extend(options, defaults);
...

```

**Comment by mathiasrw** [comment]
Did you get it tested?
