### ISSUE TITLE
Spawned processes running one after another instead of parallel

### ISSUE THREAD

**Issue by robcalcroft** [parallel-js/parallel.js#114]
I've got the syntax working and the parallel working however when I'm console logging, the spawned processes seem to be starting one after another, effectively increasing the runtime by no. of threads times. [This](https://github.com/robcalcroft/paralleladventures/blob/master/src/prime-sieve-parallel.js#L92) shows the line where I log the thread start and I get the following result in the console:

``` bash
stared thread 1458678473324
stared thread 1458678474777
stared thread 1458678476539
stared thread 1458678478468
664579 primes were found between 0 and 10000000 in 5275 milliseconds
```

The calculation is correct, just the timing seems out.

Issue continued from: https://github.com/adambom/parallel.js/issues/113

**Comment by robcalcroft** [comment]
Anyone know about this?

**Comment by robcalcroft** [comment]
@Sebmaster ?

**Comment by hy9be** [comment]
Observed similar behavior. Is it by design?

**Comment by mathiasrw** [comment]
What code are you using?
