### ISSUE TITLE
Paralleljs is 2 times slower than regular cluster fork on NodeJS

### ISSUE THREAD

**Issue by rodrigoruiz** [parallel-js/parallel.js#121]
Hi, this is more of a question, but before finding Paralleljs, I tried my own implementation of a work dispatcher and it's 2 times faster than Paralleljs, any idea why?

The details of my implementation don't matter much, I'm just using the standard cluster fork API and measuring the time to finish 20 processes.

**Comment by amilajack** [comment]
This project is pretty much deprecated. I wouldn't suggest using it. Instead, try using:

https://github.com/steelbrain/Worker-Exchange

**Comment by rodrigoruiz** [comment]
Worker-Exchange is only for the browser right?
I need it for NodeJS

**Comment by amilajack** [comment]
It is. I would recommend looking for an another alternative.

**Comment by rodrigoruiz** [comment]
Thank you for the heads up. Do you have any suggestions?

**Comment by amilajack** [comment]
For a nodejs implementation? No. But I would recommend using [npms.io](http://npms.io) to search for an alternative. Its basically like google for npm but sorts packages by code quality, maintenance, etc.

**Comment by icodeforlove** [comment]
For a isomorphic solution you can use task.js

https://github.com/icodeforlove/task.js

ps: I would love maintainer help :)
