### ISSUE TITLE
Node 6.6

### ISSUE THREAD

**Issue by mathiasrw** [parallel-js/parallel.js#123]
With node 6.6 I get a "global.env.a is not defined" error when using the example from the frontpage:

```js
var Parallel = require('paralleljs')
var p = new Parallel([1, 2, 3], {
  env: {
    a: 10
  }
});

// returns 10, 20, 30
p.map(function (d) {
  return d * global.env.a;
});
```

**Comment by linusnorton** [comment]
I am getting the same.

**Comment by amilajack** [comment]
This project is pretty much dead. I wouldn't recommend using it.

**Comment by mathiasrw** [comment]
> This project is pretty much dead. I wouldn't recommend using it.

I see - last commit was feb 2015. 

Any inputs on why its dead? 
- Lack of interest from the maintainer?
- Lack of interest from the community (other methods thats better)?

**Comment by amilajack** [comment]
I've tried to contact him on multiple occasions and he hasnt responded 😭

**Comment by mathiasrw** [comment]
Good - then he knows that there is people wanting to carry this baby

**Comment by amilajack** [comment]
He might not check the email address that I sent the message to. It was the only email I could find.

**Comment by mathiasrw** [comment]
ok - this repo is ready to get some love... I started out by adding the project page to js.org so it will soon be available as http://parallel.js.org

**Comment by amilajack** [comment]
@mathiasrw It would be great if you could add me as a collaborator. See https://github.com/parallel-js/parallel.js/pull/118#issuecomment-232420319.

**Comment by amilajack** [comment]
Never mind! I just saw that he already sent me an invitation.

**Comment by amilajack** [comment]
<img width="904" alt="screen shot 2016-09-27 at 12 03 04 pm" src="https://cloud.githubusercontent.com/assets/6374832/18887769/61192bde-84aa-11e6-845e-12b2fd1f180b.png">

Ouch. We have to fix this.

**Comment by mathiasrw** [comment]
I would like to do some minor changes in the devops here. Suggestions:

- Setup Travis-ci to verify PR's works (in node)
- Merge existing PR that can be merged
- Lean towards a git-flow attitude by keeping master branch as "last stable version" and adding updates to a new develop branch


Any objections?

**Comment by mathiasrw** [comment]
Add to the list that we must be added as collaborators to the node repo... But lets first make sure that the readme examples actually work...

**Comment by mathiasrw** [comment]
Made #126 to focus on a fresh start

**Comment by MaXwellFalstein** [comment]
I think you should do git-protect master branch and git-dev branch.

**Comment by mathiasrw** [comment]
Locked!
