### ISSUE TITLE
Migrate to SauceLabs

### ISSUE THREAD

**Issue by amilajack** [parallel-js/parallel.js#133]
[SauceLabs](saucelabs.com/) is modern browser testing automation service that can run tests against any browser on any operating system.

**Comment by mathiasrw** [comment]
https://github.com/icodeforlove/task.js is has inspiration on how to set it up

**Comment by icodeforlove** [comment]
Biggest issue was test concurrency, considering the browser matrix. So you guys may want to keep it at 1. This caused many headaches, and failed tests.

Or contribute to task.js :P.
