### ISSUE TITLE
Git-flow

### ISSUE THREAD

**Issue by mathiasrw** [parallel-js/parallel.js#134]
hi @amilajack 

If you dont mind, I would like to rename the `dev-master` to `develop` so its following the default settings for a git-flow setup for naming branches: http://danielkummer.github.io/git-flow-cheatsheet/

(so please let me know when you are not editing any new code so it can be renamed)

**Comment by amilajack** [comment]
Its good that you started the conversation about this but you didn't wait for my to response. We probably have different time zones. Please wait for feedback from other collaborators before making changes like this, PR's, closing PR's, deleting branches, and other major decisions.

**Comment by mathiasrw** [comment]
You are right. This was silly of me. 

I see you recreated the branch as it was (8 commits behind head of `master`) so thats perfect. 

I had a local copy in case something would create problems. 

> Please wait for feedback from other collaborators before making changes like this, PR's, closing PR's, deleting branches, and other major decisions.

Good point. Ill add a constriction to the develop branch so it always needs an approval from another person.
