### ISSUE TITLE
Merge changes from the Parallel2 branch

### ISSUE THREAD

**Issue by mathiasrw** [parallel-js/parallel.js#138]
https://github.com/parallel-js/parallel.js/tree/feature/MaXwellFalstein

**Comment by MaXwellFalstein** [comment]
I am happy to do the merging to the development branch, if @mathiasrw is happy.

**Comment by mathiasrw** [comment]
mathiasrw is very happy. 

I made a new branch from `develop` for you to work on: `feature/mergeFromMaxwell` (if the name is stupid, feel free to rename...)

I suggest you merge from `feature/mergeFromMaxwell` into the new branch instead of into `develop`

**Comment by MaXFalstein** [comment]
# Everything from Parallel2.js has been migrated.

**Comment by mathiasrw** [comment]
Great work @MaXFalstein !
