### ISSUE TITLE
PR: Migrate to webpack for buld system

### ISSUE THREAD

**Issue by mathiasrw** [parallel-js/parallel.js#145]
I suggest we use gulp to generate a .min version so we can autopublish to a CDN (#140)

I also suggest we put the source in `src/` and let gulp build to `lib`.

Any objections/inputs?

This should only be done after code from #138 is merged in.

**Comment by amilajack** [comment]
Webpack is optimal for this.

**Comment by mathiasrw** [comment]
Lets use webpack

**Comment by amilajack** [comment]
Agreed.

**Comment by MaXwellFalstein** [comment]
Have we changed to webpack on one of the dev branches yet?

#145

**Comment by mathiasrw** [comment]
Not that I know of... @amilajack ?

**Comment by amilajack** [comment]
Its been a while. I'm not sure exactly

**Comment by MaXFalstein** [comment]
#138 has been completed. Now this can be completed and we can move onto #140.
