### ISSUE TITLE
First Timers PR's

### ISSUE THREAD

**Issue by MaXFalstein** [parallel-js/parallel.js#152]
I think we should actively promote first timers to enacting a pull request for an addition or a fix.

I think we should try to get first timers to build example web sites to show potential users how to use Parallel.js.

[Parallel2.js/Issues/FirstTimers](https://github.com/MaXwellFalstein/Parallel2.js/issues/8) is the issue I started for trying to set this up for (the now defunct) Parallel2.js.

**Comment by mathiasrw** [comment]
So - its a branch called something like "first-timers" where we are more easy on the PR?

Sound fine to me...

**Comment by MaXwellFalstein** [comment]
I think we should do a special branch for first-timers and look at up-for-grabls initiative.

I have created a new [branch]() for README updates including [adding the first-timers logo](https://github.com/parallel-js/parallel.js/commit/1d16f1ebeaaae38f162904ef5fdb023b3181becc).

#1d16f1e
