### ISSUE TITLE
Discussion: Logo Idea

### ISSUE THREAD

**Issue by amilajack** [parallel-js/parallel.js#153]
I think we should consider a logo for this repo. Having a logo can help this project become more recognized.

Any ideas?

**Comment by mathiasrw** [comment]
Good idea. Lets post all inputs here and vote for the ones we like

**Comment by mathiasrw** [comment]
![a](https://cloud.githubusercontent.com/assets/1063454/19116233/04572696-8b15-11e6-918a-fff7a05eb59f.png)

**Comment by mathiasrw** [comment]
![b](https://cloud.githubusercontent.com/assets/1063454/19116246/0d01dcd2-8b15-11e6-8a8e-d4d8a36ca2bf.png)

**Comment by mathiasrw** [comment]
![c](https://cloud.githubusercontent.com/assets/1063454/19116249/10f7c9f0-8b15-11e6-95e3-9a1329a7dded.png)

**Comment by mathiasrw** [comment]
![d](https://cloud.githubusercontent.com/assets/1063454/19116252/142664e2-8b15-11e6-9610-688295cdd6be.png)

**Comment by amilajack** [comment]
IMO this seems a lot cleaner
<img width="215" alt="screen shot 2016-10-05 at 7 43 46 am" src="https://cloud.githubusercontent.com/assets/6374832/19122628/375df5b8-8ae0-11e6-87a5-3df44de853e0.png">

**Comment by amilajack** [comment]
<img width="422" alt="screen shot 2016-10-05 at 10 00 53 am" src="https://cloud.githubusercontent.com/assets/6374832/19123221/a0653ad8-8ae2-11e6-8a50-77bac1afe32c.png">

**Comment by mathiasrw** [comment]
The `||P` one has some interesting ideas. 

The `//` one brings the mind to two slashes - maybe if we turn them some more?

**Comment by amilajack** [comment]
I agree

**Comment by amilajack** [comment]
Seems like the last one got the most votes. Lets go with that one.

**Comment by mathiasrw** [comment]
Cool. If you can make it into a vector file that would be great. Maybe host it no the gh-pages branch?
