### ISSUE TITLE
unable to resolve module os 

### ISSUE THREAD

**Issue by hasancanozkan** [parallel-js/parallel.js#166]
Hi folks, I am using the last version of paralleljs --> 0.2.1 and ReactNative 0.46.4. 

I just tried a simple code to use paralleljs, basically to understand it, but I am getting unable to resolve module os from ../lib/parallel.js 

has anyone faced the same issue before?

**Comment by mathiasrw** [comment]
Why would it be abandoned?

**Comment by hasancanozkan** [comment]
I was just checking the issues,.. nevermind, I have another question actually, I couldnt even run RN code after installing paralleljs, giving this issue unable to resolve module os from ../lib/parallel.js

**Comment by mathiasrw** [comment]
RN?

**Comment by hasancanozkan** [comment]
React-Native

**Comment by hasancanozkan** [comment]
![img_1309](https://user-images.githubusercontent.com/15143230/30030383-3ce23d3c-918d-11e7-93b9-58428be27e6c.JPG)

**Comment by hasancanozkan** [comment]
I understood the issue: 'os' is a module for node.js only, it is not compatible with React-Native, therefore I cant use it, and as I check the code deeply there are other modules which only belong to Node. I wish It would be a pure JS code..
