### ISSUE TITLE
Site Broken?

### ISSUE THREAD

**Issue by davidhbigelow** [parallel-js/parallel.js#183]
The site seems to broken and the project failing?

**Comment by tonetechnician** [comment]
Yeah! Would love a follow up on this. Have been testing some of the code examples and it seems the 'Passing environment to functions' example doesn't work. 

Is this code only compatible with certain nodejs versions?

**Comment by tonetechnician** [comment]
Is there anyone able to say? Is the project dead?

**Comment by WhiteBookmark** [comment]
Is this project dead ?

**Comment by mathiasrw** [comment]
A bit dead
