### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by jdb8** [parallel-js/parallel.js#184]
## Prerequisites

- [ ] Using yarn
- [ ] Using an up-to-date master branch
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

The version available on npm should be the same as the version on github master.

## Current Behavior

The version on npm is 0.2.1 while the package.json on master is 0.3.0: https://www.npmjs.com/package/paralleljs vs https://github.com/parallel-js/parallel.js/blob/5fe4970ecedbb1c20646dcdccd28d0650c81af76/package.json#L3

## Possible Solution

Release 0.3.0 on npm. Even better would be to release a v0.2.2 which fixes the issue outlined below ([this commit](https://github.com/parallel-js/parallel.js/commit/e1b71c06b89d5b00aea28180017417ea4c8e5508#diff-b9cfc7f2cdf78a7f4b91a753d10865a2)).

## Steps to Reproduce (for bugs)

N/A

## Context

There's a specific issue with v0.2.1 which is the zero-width spaces present in the package.json. This was fixed in [this commit](https://github.com/parallel-js/parallel.js/commit/e1b71c06b89d5b00aea28180017417ea4c8e5508#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) but hasn't been released yet. It means that packages depending on paralleljs are pulling in a broken package.json, which breaks some tooling that tries to parse package.json files inside node_modules.

## Your Environment

- Node version : any
- Version or Branch used : v0.2.1
- Operating System and version : any
- Link to your project : n/a

**Comment by mathiasrw** [comment]
Good point. Lets get it flying.

**Comment by jdb8** [comment]
Any update on this?

**Comment by jdb8** [comment]
Bump - @mathiasrw, not sure if you have access to release a new version, but this would still be useful.

**Comment by mathiasrw** [comment]
@jdb8 Let me see what I can do.

**Comment by mathiasrw** [comment]
@adambom @Sebmaster @MaXFalstein @amilajack @vikr01 

Any objections to releasing the current version?

**Comment by mathiasrw** [comment]
@adambom @Sebmaster @MaXFalstein @amilajack @vikr01

I am intending to release a new version npm if I hear nothing from you.

**Comment by amilajack** [comment]
There is actually no new version. I reverted that work because it makes too many breaking changes.

**Comment by jdb8** [comment]
@amilajack to clarify: https://github.com/parallel-js/parallel.js/commit/e1b71c06b89d5b00aea28180017417ea4c8e5508 was reverted? The only reason I personally wanted a new version was because the version that's latest on npm has a broken package.json, which breaks some tooling. It's fine (and actually preferable) if the next release is a patch 0.2.2 which solely includes that commit.

**Comment by amilajack** [comment]
@mathiasrw pushed some changes and fixes. Would love if you could bump package to `0.3.0`. I dont have publishing permission.

@jdb8 After publishing a new version, it should work
