### ISSUE TITLE
async functions / examples

### ISSUE THREAD

**Issue by tp** [parallel-js/parallel.js#39]
Is it possible to use `parallel.js` with function that have take a callback to deliver the results?

**Comment by nickpoorman** [comment]
+1 This library would become extremely powerful if it had the ability to do async functions inside a Parallel function. Obviously the Parallel function would need to utilize a callback.

**Comment by bportnoy** [comment]
+1 on this as well - looking at it from the same perspective as @nickpoorman.

**Comment by juanluidos** [comment]
Is there still no support for it?
