### ISSUE TITLE
Access to the workers `.terminate()` API

### ISSUE THREAD

**Issue by jpillora** [parallel-js/parallel.js#52]
I'd like to have timeouts, though it seems there is no way to cancel running workers?

**Comment by Shadowstep33** [comment]
Well since no one seemed to address this, here is how I did:

parallel.js
```
:211 + that.workerProcess = wrk;
```

and in my code

```
char.pO = par.spawn(Synapse.updatePlayer).then(eLog);

...//later..

crit.pO.workerProcess.process.kill();
```

I tried to use .terminate, but it was not found as a function
