### ISSUE TITLE
BUG: paralleljs fails in browserify

### ISSUE THREAD

**Issue by eugeneware** [parallel-js/parallel.js#56]
When I try to use paralleljs in browserify with the following code:

``` js
// test.js
var Parallel = require('paralleljs');
var p = new Parallel('forwards');
p.spawn(function (data) {
  data = data.split('').reverse().join('');
  console.log(data); // logs sdrawrof
  return data;
}).then(function (data) {
  console.log(data) // logs sdrawrof
});
```

And then I compile it:

```
$ npm install -g browserify
$ browserify test.js > bundle.js
```

And then I include it in a simple HTML page:

``` html
<!DOCTYPE html>
<script src="bundle.js"></script>
```

I get the following errors in Chrome:

```
Uncaught Error: Cannot find module '/node_modules/paralleljs/lib/Worker.js' bundle.js:1
s bundle.js:1
(anonymous function) bundle.js:1
(anonymous function) bundle.js:54
os bundle.js:358
s bundle.js:1
(anonymous function) bundle.js:1
paralleljs bundle.js:360
s bundle.js:1
e bundle.js:1
(anonymous function)
```

I know you can just include parallels directly as a script tag, but would be nice to use this within browserify.

**Comment by magus** [comment]
Seeing this same issue on 0.2.1 and browserify 9.0.3

**Comment by crubier** [comment]
Same problem Here. Compiling with browserify and babelJS.

When executing on Safari I find no problem.

When executing on Chrome i get this error: Cannot find module '/node_modules/paralleljs/lib/Worker.js'

**Comment by flaszer** [comment]
Got exactly the same issue - tested on Chrome.

**Comment by imsky** [comment]
+1

**Comment by gaplo917** [comment]
found a solution if you are playing with browserify and babelJS.

replace line 3 from
```javascript
var isNode = typeof global !== "undefined" && {}.toString.call(global) == '[object global]';
```

to 
```javascript
var isNode = !(typeof window !== 'undefined' && this === window);
```

Have fun with paralleljs 
`var Parallel = require('paralleljs');`
