### ISSUE TITLE
Progress events

### ISSUE THREAD

**Issue by yetithefoot** [parallel-js/parallel.js#61]
Hey.

I do heavy operation in worker method and want to notify caller about calculating progress. By using clean WebWorkers I can send postMessages with progress object.

Is there any way to send progress events from worker using Parallel?

**Comment by amergin** [comment]
@Sebmaster: there are pull requests https://github.com/adambom/parallel.js/pull/96 and https://github.com/adambom/parallel.js/pull/86 open about this.

**Comment by amergin** [comment]
Any news on this? Is this repo still maintained?

**Comment by mathiasrw** [comment]
@amergin 

This repo has just got some new blood and the PRs are starting to flow again

[![Throughput Graph](https://graphs.waffle.io/parallel-js/parallel.js/throughput.svg)](https://waffle.io/parallel-js/parallel.js/metrics/throughput)
