### ISSUE TITLE
Passing data with "transfer-by-ownership" 

### ISSUE THREAD

**Issue by idoodler** [parallel-js/parallel.js#88]
Hi, I am looking for a way to pass big amount of data from the main-thread to the worker-thread, I have read from "transfer-by-ownership" when working with Webworkers, but I am not able to find this option on Parallel.js. Am I missing something?

Have a nice day,
David

**Comment by amergin** [comment]
+1 as well.

**Comment by lukewestby** [comment]
+1

**Comment by steveftoth** [comment]
+1
