### ISSUE TITLE
[BUG] paralleljs fails in browserify

### ISSUE THREAD

**Issue by magus** [parallel-js/parallel.js#98]
Loading the NPM version of paralleljs in the browser produces the following error

```
Uncaught Error: Cannot find module '/node_modules/paralleljs/lib/Worker.js'_prelude.js:1
```

Doesn't appear to be related to browserify, like #56 with the same error. The NPM version of parallel.js simply seems to have an incorrect line 3 in the parallel.js file, see comment below.

**Comment by magus** [comment]
After poking around a bit I think it might be due to this line of code being different in the NPM version of the file.

https://github.com/adambom/parallel.js/blob/master/lib/parallel.js#L3

`npm install paralleljs` returns the following L3
```javascript
var isNode = typeof global !== "undefined" && {}.toString.call(global) == '[object global]';
```

The critical `!(...)` surrounding the isNode variable is missing which causes the variable to evaluate to true in the browser, attempt to load the Worker.js file, and subsequently fail. If I forcefully make the 'isNode' variable evaluate to false, things work as expected.

**Comment by Sebmaster** [comment]
That line is already changed in [master](https://github.com/adambom/parallel.js/blob/ee3661780edb8e9ab34136315c0b4a030328865f/lib/parallel.js#L2-L3) and I can't update the npm version. Need @adambom for that.

**Comment by magus** [comment]
That explains the inconsistency, I've updated my local copy for the time being.
